apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-pv
  labels:
    name: nginx-storage
spec:
  storageClassName: manual 
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/docker/data"